#!/usr/bin/env php
<?php

/**
 * ECTouch - A Modern E-Commerce Platform
 *
 * @package  ECTouch
 * @homepage https://ectouch.cn
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// register commands
foreach (glob(app_path('Command/*Command.php')) as $command) {
    $command = '\\App\\Command\\' . basename($command, '.php');
    $app->add(new $command());
}

$app->run();
