#!/usr/bin/env php
<?php

/**
 * ECTouch - A Modern E-Commerce Platform
 *
 * @package  ECTouch
 * @homepage https://ectouch.cn
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// register commands
foreach (glob(app_path('Command/*Command.php')) as $command) {
    $command = '\\App\\Command\\' . basename($command, '.php');
    $app->add(new $command());
}

$app->addCommands([
    new \Phinx\Console\Command\Init(),
    new \Phinx\Console\Command\Create(),
    new \Phinx\Console\Command\Migrate(),
    new \Phinx\Console\Command\Rollback(),
    new \Phinx\Console\Command\Status(),
    new \Phinx\Console\Command\Breakpoint(),
    new \Phinx\Console\Command\Test(),
    new \Phinx\Console\Command\SeedCreate(),
    new \Phinx\Console\Command\SeedRun()
]);

$app->run();
