#!/usr/bin/env php
<?php

/**
 * ECTouch - A Modern E-Commerce Platform
 *
 * @package  ECTouch
 * @homepage https://ectouch.cn
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// register commands
$app->add(new \App\Command\CreateUserCommand());

$app->run();
